#        **Analyse et nettoyage du dataset BAAC – France 2024**

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [118]:
caract = pd.read_csv("caract-2024.csv", sep=";", encoding="utf-8", low_memory=False)
lieux = pd.read_csv("lieux-2024.csv", sep=";", encoding="utf-8", low_memory=False)
vehicules = pd.read_csv("vehicules-2024.csv", sep=";", encoding="utf-8", low_memory=False)
usagers = pd.read_csv("usagers-2024.csv", sep=";", encoding="utf-8", low_memory=False)

#### **1) Nettoyage de la table `caract` (Caractéristique des accidents)**

1.1 Exploration initiale

In [119]:
print("Les colonnes de la table caract :\n")
print(caract.columns)
print("\n")
print("Les différentes infos de la table :\n")
print(caract.info)
print("\n")
print("Apperçu de la table : \n")
caract.head()

Les colonnes de la table caract :

Index(['Num_Acc', 'jour', 'mois', 'an', 'hrmn', 'lum', 'dep', 'com', 'agg',
       'int', 'atm', 'col', 'adr', 'lat', 'long'],
      dtype='str')


Les différentes infos de la table :

<bound method DataFrame.info of             Num_Acc  jour  mois    an   hrmn  lum dep    com  agg  int  atm  \
0      202400000001    25     3  2024  07:40    2  70  70285    1    1    5
1      202400000002    20     3  2024  15:05    1  21  21054    2    3    7
2      202400000003    22     3  2024  19:30    2  15  15012    1    1    1
3      202400000004    24     3  2024  17:50    1  14  14118    2    3    7
4      202400000005    25     3  2024  19:35    5  13  13106    1    3    2
...             ...   ...   ...   ...    ...  ...  ..    ...  ...  ...  ...
54397  202400054398    10     7  2024  02:05    5  94  94065    2    3    2
54398  202400054399    30    11  2024  15:27    1  92  92062    2    1    1
54399  202400054400    24    10  2024  20:40    3  29  29068    1    1    1
54400  202400054401    30    11  2024  15:40    1  92  92012    2    1    1
54401  202400054402    10     7  2024  08:30    1  94  94028    2    1    1

       col                                      adr          lat          long
0        1                                     D438  47,56277000    6,75832000
1        6                   HOTEL DIEU (RUE DE L')  47,02109000    4,83755000
2        6                       Allée des Tilleuls  44,90238400    2,49641800
3        3                         128 Rue d'Authie  49,19166000   -0,39851000
4        5                   BEDOULE (CHEMIN DE LA)  43,39000000    5,35000000
...    ...                                      ...          ...           ...
54397    6                 Avenue Charles Lindbergh  48,75740000    2,34469000
54398    6                        RUE PIERRE GAUDIN  48,88694322    2,24863619
54399    1                          PK 031.950 RN12  48,52619024   -3,96317650
54400    3  JEAN JAURES (BOULEVARD) 63/215 - 70/208  48,83286197    2,24394009
54401    4                   Avenue de la Pompadour  48,78330000    2,46660000

[54402 rows x 15 columns]>


Apperçu de la table :

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
0,202400000001,25,3,2024,07:40,2,70,70285,1,1,5,1,D438,"47,56277000","6,75832000"
1,202400000002,20,3,2024,15:05,1,21,21054,2,3,7,6,HOTEL DIEU (RUE DE L'),"47,02109000","4,83755000"
2,202400000003,22,3,2024,19:30,2,15,15012,1,1,1,6,Allée des Tilleuls,"44,90238400","2,49641800"
3,202400000004,24,3,2024,17:50,1,14,14118,2,3,7,3,128 Rue d'Authie,"49,19166000","-0,39851000"
4,202400000005,25,3,2024,19:35,5,13,13106,1,3,2,5,BEDOULE (CHEMIN DE LA),"43,39000000","5,35000000"

In [120]:
print("Les différents types des attributs de l'entité : \n")
print(caract.dtypes)

Les différents types des attributs de l'entité :

Num_Acc    int64
jour       int64
mois       int64
an         int64
hrmn         str
lum        int64
dep          str
com          str
agg        int64
int        int64
atm        int64
col        int64
adr          str
lat          str
long         str
dtype: object

Analyse des doublons et des valeurs manquantes

In [121]:
print("Nombre de doublons : ", + caract.duplicated().sum())
print("\n")
print("Nombre de cellule vide dans chaque colonne : \n")
print(caract.isna().sum())

Nombre de doublons :  0


Nombre de cellule vide dans chaque colonne :

Num_Acc       0
jour          0
mois          0
an            0
hrmn          0
lum           0
dep           0
com           0
agg           0
int           0
atm           0
col           0
adr        2310
lat           0
long          0
dtype: int64

Il y a donc pas de doublon présent dans la table et il y a des valeurs manquates dans adr à la place des cases vides on va mettre des Unknown pour dire que l'adresse est inconnue

In [122]:
caract["adr"] = caract["adr"].fillna("Unknown")             # remplacement des cases vides
caract["adr"].isna().sum()                                  # Vérification du remplacement

np.int64(0)

Vérification des valeurs abérrantes

In [109]:
caract.describe(include= 'all')

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
count,5.440200e+04,54402.000000,54402.000000,54402.0,54402,54402.000000,54402,54402,54402.000000,54402.000000,54402.000000,54402.000000,54402,54402,54402
unique,NaN,NaN,NaN,NaN,1414,NaN,107,11285,NaN,NaN,NaN,NaN,28872,52471,52742
top,NaN,NaN,NaN,NaN,18:00,NaN,75,97302,NaN,NaN,NaN,NaN,Unknown,"48,91936344","5,40000000"
freq,NaN,NaN,NaN,NaN,677,NaN,4191,479,NaN,NaN,NaN,NaN,2310,8,9
mean,2.024000e+11,15.665490,6.615749,2024.0,NaN,1.949708,NaN,NaN,1.625161,2.108195,1.677493,4.018069,NaN,NaN,NaN
std,1.570465e+04,8.737761,3.361701,0.0,NaN,1.488462,NaN,NaN,0.484086,2.042602,1.736956,1.984560,NaN,NaN,NaN
min,2.024000e+11,1.000000,1.000000,2024.0,NaN,1.000000,NaN,NaN,1.000000,1.000000,1.000000,-1.000000,NaN,NaN,NaN
25%,2.024000e+11,8.000000,4.000000,2024.0,NaN,1.000000,NaN,NaN,1.000000,1.000000,1.000000,3.000000,NaN,NaN,NaN
50%,2.024000e+11,16.000000,7.000000,2024.0,NaN,1.000000,NaN,NaN,2.000000,1.000000,1.000000,3.000000,NaN,NaN,NaN
75%,2.024000e+11,23.000000,10.000000,2024.0,NaN,3.000000,NaN,NaN,2.000000,2.000000,1.000000,6.000000,NaN,NaN,NaN
max,2.024001e+11,31.000000,12.000000,2024.0,NaN,5.000000,NaN,NaN,2.000000,9.000000,9.000000,7.000000,NaN,NaN,NaN

Pas de valeur aberrante le min et le max de chaque attribut est respecté

In [123]:
caract["date"] = pd.to_datetime({
    "year": caract["an"],
    "month": caract["mois"],
    "day": caract["jour"],
})

caract.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long,date
0,202400000001,25,3,2024,07:40,2,70,70285,1,1,5,1,D438,"47,56277000","6,75832000",2024-03-25
1,202400000002,20,3,2024,15:05,1,21,21054,2,3,7,6,HOTEL DIEU (RUE DE L'),"47,02109000","4,83755000",2024-03-20
2,202400000003,22,3,2024,19:30,2,15,15012,1,1,1,6,Allée des Tilleuls,"44,90238400","2,49641800",2024-03-22
3,202400000004,24,3,2024,17:50,1,14,14118,2,3,7,3,128 Rue d'Authie,"49,19166000","-0,39851000",2024-03-24
4,202400000005,25,3,2024,19:35,5,13,13106,1,3,2,5,BEDOULE (CHEMIN DE LA),"43,39000000","5,35000000",2024-03-25

On peut donc supprimer les attributs jour mois et an

In [131]:
caract.drop(["jour", "mois", "an"], axis=1, inplace=True)

In [132]:
caract.head()

,Num_Acc,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long,date
0,202400000001,07:40,2,70,70285,1,1,5,1,D438,"47,56277000","6,75832000",2024-03-25
1,202400000002,15:05,1,21,21054,2,3,7,6,HOTEL DIEU (RUE DE L'),"47,02109000","4,83755000",2024-03-20
2,202400000003,19:30,2,15,15012,1,1,1,6,Allée des Tilleuls,"44,90238400","2,49641800",2024-03-22
3,202400000004,17:50,1,14,14118,2,3,7,3,128 Rue d'Authie,"49,19166000","-0,39851000",2024-03-24
4,202400000005,19:35,5,13,13106,1,3,2,5,BEDOULE (CHEMIN DE LA),"43,39000000","5,35000000",2024-03-25

Certains attributs de la table **caractéristiques** apparaissent au format texte (`str`) en raison de la présence de valeurs vides ou de formats mixtes. Les colonnes géographiques (`lat`, `long`) ont été converties en numérique après nettoyage, tandis que les codes administratifs (`dep`, `com`) ont été conservés en texte pour préserver les zéros initiaux.

In [ ]:
caract["lat"] = caract["lat"].str.replace(",", ".").astype(float)
caract["long"] = caract["long"].str.replace(",", ".").astype(float)

Les attributs `dep` et `com` ont été conservés au format texte (`str`) car ils représentent des codes administratifs. Une conversion en entier supprimerait les zéros initiaux (ex. `075` → `75`), ce qui altérerait la précision des identifiants géographiques.


L’attribut `hrmn` a été conservé au format texte (`str`) car il représente un code horaire (HHMM). Une conversion en entier supprimerait les zéros initiaux (ex. `0835` → `835`), ce qui altérerait l’information. Le format texte est donc le plus adapté pour préserver la structure du code.

#### **2) Nettoyage de la table lieux**

In [168]:
print("Les colonnes de la table lieux :\n")
print(lieux.columns)
print("\n")
print("Les différentes infos de la table :\n")
print(lieux.info)
print("\n")
print("Apperçu de la table : \n")
lieux.head()

Les colonnes de la table lieux :

Index(['Num_Acc', 'catr', 'voie', 'v1', 'v2', 'circ', 'nbv', 'vosp', 'prof',
       'pr', 'pr1', 'plan', 'lartpc', 'larrout', 'surf', 'infra', 'situ',
       'vma'],
      dtype='str')


Les différentes infos de la table :

<bound method DataFrame.info of             Num_Acc  catr                                     voie  v1   v2  \
0      202400000001     3                                     D438   0  NaN
1      202400000002     4                   HOTEL DIEU (RUE DE L')   0  NaN
2      202400000002     4                            POTERNE (RUE)   0  NaN
3      202400000003     4                     TILLEULS (ALLEE DES)   0  NaN
4      202400000004     4       AUTHIE (N° 106 PAIRS -115 IMPAIRS)   0  NaN
...             ...   ...                                      ...  ..  ...
70243  202400054398     3                                      NaN  -1  NaN
70244  202400054399     3                        RUE PIERRE GAUDIN   0  NaN
70245  202400054400     2                                       12   0  NaN
70246  202400054401     3  JEAN JAURES (BOULEVARD) 63/215 - 70/208   0  NaN
70247  202400054402     3                                       86   0  NaN

       circ nbv  vosp  prof   pr    pr1  plan lartpc larrout  surf  infra  \
0         2   2     0     1    1    260     2    NaN       7     1      0
1         2   2     0     1   -1     -1     1    NaN      -1     9      0
2         1   1     0     1   -1     -1     1    NaN      -1     9      0
3         2   2     0     1   -1     -1     1    NaN      -1     1      0
4         2   4     0     1   -1     -1     1    NaN      -1     1      9
...     ...  ..   ...   ...  ...    ...   ...    ...     ...   ...    ...
70243     1   1    -1     1   -1     -1     1    NaN      -1     2      5
70244     1   1     2     1    0      0     2    NaN      -1     1      0
70245     1   2     0     2   31  1 000     1    NaN      10     1      0
70246     2   3     0     1    0      0     1    NaN    10,5     1      0
70247     1   2     0     2    0      0     1    NaN      -1     1      2

       situ  vma
0         1   90
1         1   30
2         1   30
3         3   50
4         1   50
...     ...  ...
70243     4   -1
70244     1   30
70245     1  110
70246     1   50
70247     1   50

[70248 rows x 18 columns]>


Apperçu de la table :

,Num_Acc,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma
0,202400000001,3,D438,0,NaN,2,2,0,1,1,260,2,NaN,7,1,0,1,90
1,202400000002,4,HOTEL DIEU (RUE DE L'),0,NaN,2,2,0,1,-1,-1,1,NaN,-1,9,0,1,30
2,202400000002,4,POTERNE (RUE),0,NaN,1,1,0,1,-1,-1,1,NaN,-1,9,0,1,30
3,202400000003,4,TILLEULS (ALLEE DES),0,NaN,2,2,0,1,-1,-1,1,NaN,-1,1,0,3,50
4,202400000004,4,AUTHIE (N° 106 PAIRS -115 IMPAIRS),0,NaN,2,4,0,1,-1,-1,1,NaN,-1,1,9,1,50

In [180]:
print("Le nombre de cellule vide dans chaque colonne : \n")
print(lieux.isna().sum())
print("\n")
print("Le nombre de doublons dans la table :", +lieux.duplicated().sum())
print("\n")
print("Visuel des lignes doublées :")
lieux[lieux.duplicated(keep=False)]

Le nombre de cellule vide dans chaque colonne :

Num_Acc        0
catr           0
voie       13331
v1             0
v2         64332
circ           0
nbv            0
vosp           0
prof           0
pr             0
pr1            0
plan           0
lartpc     70215
larrout        0
surf           0
infra          0
situ           0
vma            0
dtype: int64


Le nombre de doublons dans la table : 2


Visuel des lignes doublées :

,Num_Acc,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma
15884,202400012279,3,NaN,-1,NaN,2,-1,-1,2,-1,-1,1,NaN,-1,1,0,1,-1
15885,202400012279,3,NaN,-1,NaN,2,-1,-1,2,-1,-1,1,NaN,-1,1,0,1,-1
57342,202400044389,4,NaN,-1,NaN,2,-1,-1,1,-1,-1,1,NaN,-1,1,0,1,-1
57343,202400044389,4,NaN,-1,NaN,2,-1,-1,1,-1,-1,1,NaN,-1,1,0,1,-1

Les doublons observés dans la table **lieux** correspondent à des lignes strictement identiques pour un même numéro d’accident. Comme chaque accident ne doit être associé qu’à un seul lieu, ces répétitions traduisent une **erreur de saisie ou d’importation** plutôt qu’une situation réelle.
Il y a également des cellules vide notamment dans **lartpc** **v2** et **voie**

In [182]:
lieux.dtypes

Num_Acc    int64
catr       int64
voie         str
v1         int64
v2           str
circ       int64
nbv          str
vosp       int64
prof       int64
pr           str
pr1          str
plan       int64
lartpc       str
larrout      str
surf       int64
infra      int64
situ       int64
vma        int64
dtype: object

Correction des valeurs manquantes en ajoutant `Unknown`

In [186]:
lieux["voie"] = lieux["voie"].fillna("Unknown")
lieux["v2"] = lieux["v2"].fillna("Unknown")
lieux["lartpc"] = lieux["lartpc"].fillna("Unknown")

print("Nombre de valeurs manquantes après correction : \n")
print(lieux.isna().sum())

Nombre de valeurs manquantes après correction :

Num_Acc    0
catr       0
voie       0
v1         0
v2         0
circ       0
nbv        0
vosp       0
prof       0
pr         0
pr1        0
plan       0
lartpc     0
larrout    0
surf       0
infra      0
situ       0
vma        0
dtype: int64

Pour les attributs `voie`, `v2` et `lartpc`  les cellules vides ont été remplacées par la valeur `Unknown`. Comme il s’agit d’attributs catégoriel et non numérique, cette substitution est cohérente : elle permet d’indiquer explicitement que le type de voie n’est pas renseigné, sans introduire de valeur artificielle.

Suppresion des doublons

In [190]:
lieux = lieux.drop_duplicates(lieux) # Suppresion des doublons
print("Nombre de ligne doublés après corréction :", +lieux.duplicated().sum())

Nombre de ligne doublés après corréction : 0

In [192]:
lieux.describe()

,Num_Acc,catr,v1,circ,vosp,prof,plan,surf,infra,situ,vma
count,7.024600e+04,70246.000000,70246.000000,70246.000000,70246.000000,70246.000000,70246.000000,70246.000000,70246.000000,70246.000000,70246.000000
mean,2.024000e+11,3.401574,-0.228255,1.735615,0.185904,1.215699,1.278037,1.283660,0.847934,1.640150,53.713037
std,1.570886e+04,1.123817,0.432342,0.908136,0.745741,0.527899,0.656018,0.808311,2.201933,1.676752,27.237056
min,2.024000e+11,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,2.024000e+11,3.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,30.000000
50%,2.024000e+11,3.000000,0.000000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,50.000000
75%,2.024000e+11,4.000000,0.000000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,70.000000
max,2.024001e+11,9.000000,3.000000,4.000000,3.000000,4.000000,4.000000,9.000000,9.000000,8.000000,900.000000

L’analyse statistique des attributs de la table `lieux` révèle aucune valeur aberrante. Les valeurs extrêmes observées (ex. -1 ou 900) correspondent à des codes BAAC indiquant des données non renseignées ou sans objet, et sont donc cohérentes avec la nomenclature officielle.

In [196]:
lieux["lartpc"].unique()

<StringArray>
['Unknown',       '7',       '2',      '10',       '3',     '3,5',       '9',
       '4',      '14',     '4,5',       '5',     '2,5',     '8,5',       '1',
      '12',     '6,2']
Length: 16, dtype: str

On remarque de l'attribut `lartpc` peut etre convertit en int pour faciliter l'analyse après

In [ ]:
lieux["lartpc"] = (
    lieux["lartpc"]
    .replace("Unknown", np.nan)
    .astype(float)
)

print("Nouveau type de l'attribut lartpc  ",  lieux["lartpc"].dtypes)

Nouveau type de l'attribut lartpc :  float64