In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [118]:
caract = pd.read_csv("caract-2024.csv", sep=";", encoding="utf-8", low_memory=False)
lieux = pd.read_csv("lieux-2024.csv", sep=";", encoding="utf-8", low_memory=False)
vehicules = pd.read_csv("vehicules-2024.csv", sep=";", encoding="utf-8", low_memory=False)
usagers = pd.read_csv("usagers-2024.csv", sep=";", encoding="utf-8", low_memory=False)

1) ANALYSE DE LA TABLE CARACT (Représente les Caractéristique des accidents enregistrés)

1.1 Exploration initiale

In [119]:
print("Les colonnes de la table caract :\n")
print(caract.columns)
print("\n")
print("Les différentes infos de la table :\n")
print(caract.info)
print("\n")
print("Apperçu de la table : \n")
caract.head()

Les colonnes de la table caract :

Index(['Num_Acc', 'jour', 'mois', 'an', 'hrmn', 'lum', 'dep', 'com', 'agg',
       'int', 'atm', 'col', 'adr', 'lat', 'long'],
      dtype='str')


Les différentes infos de la table :

<bound method DataFrame.info of             Num_Acc  jour  mois    an   hrmn  lum dep    com  agg  int  atm  \
0      202400000001    25     3  2024  07:40    2  70  70285    1    1    5
1      202400000002    20     3  2024  15:05    1  21  21054    2    3    7
2      202400000003    22     3  2024  19:30    2  15  15012    1    1    1
3      202400000004    24     3  2024  17:50    1  14  14118    2    3    7
4      202400000005    25     3  2024  19:35    5  13  13106    1    3    2
...             ...   ...   ...   ...    ...  ...  ..    ...  ...  ...  ...
54397  202400054398    10     7  2024  02:05    5  94  94065    2    3    2
54398  202400054399    30    11  2024  15:27    1  92  92062    2    1    1
54399  202400054400    24    10  2024  20:40    3  29  29068    1    1    1
54400  202400054401    30    11  2024  15:40    1  92  92012    2    1    1
54401  202400054402    10     7  2024  08:30    1  94  94028    2    1    1

       col                                      adr          lat          long
0        1                                     D438  47,56277000    6,75832000
1        6                   HOTEL DIEU (RUE DE L')  47,02109000    4,83755000
2        6                       Allée des Tilleuls  44,90238400    2,49641800
3        3                         128 Rue d'Authie  49,19166000   -0,39851000
4        5                   BEDOULE (CHEMIN DE LA)  43,39000000    5,35000000
...    ...                                      ...          ...           ...
54397    6                 Avenue Charles Lindbergh  48,75740000    2,34469000
54398    6                        RUE PIERRE GAUDIN  48,88694322    2,24863619
54399    1                          PK 031.950 RN12  48,52619024   -3,96317650
54400    3  JEAN JAURES (BOULEVARD) 63/215 - 70/208  48,83286197    2,24394009
54401    4                   Avenue de la Pompadour  48,78330000    2,46660000

[54402 rows x 15 columns]>


Apperçu de la table :

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
0,202400000001,25,3,2024,07:40,2,70,70285,1,1,5,1,D438,"47,56277000","6,75832000"
1,202400000002,20,3,2024,15:05,1,21,21054,2,3,7,6,HOTEL DIEU (RUE DE L'),"47,02109000","4,83755000"
2,202400000003,22,3,2024,19:30,2,15,15012,1,1,1,6,Allée des Tilleuls,"44,90238400","2,49641800"
3,202400000004,24,3,2024,17:50,1,14,14118,2,3,7,3,128 Rue d'Authie,"49,19166000","-0,39851000"
4,202400000005,25,3,2024,19:35,5,13,13106,1,3,2,5,BEDOULE (CHEMIN DE LA),"43,39000000","5,35000000"

In [120]:
print("Les différents types des attributs de l'entité : \n")
print(caract.dtypes)

Les différents types des attributs de l'entité :

Num_Acc    int64
jour       int64
mois       int64
an         int64
hrmn         str
lum        int64
dep          str
com          str
agg        int64
int        int64
atm        int64
col        int64
adr          str
lat          str
long         str
dtype: object

Analyse des doublons et des valeurs manquantes

In [121]:
print("Nombre de doublons : ", + caract.duplicated().sum())
print("\n")
print("Nombre de cellule vide dans chaque colonne : \n")
print(caract.isna().sum())

Nombre de doublons :  0


Nombre de cellule vide dans chaque colonne :

Num_Acc       0
jour          0
mois          0
an            0
hrmn          0
lum           0
dep           0
com           0
agg           0
int           0
atm           0
col           0
adr        2310
lat           0
long          0
dtype: int64

Il y a donc pas de doublon présent dans la table et il y a des valeurs manquates dans adr à la place des cases vides on va mettre des Unknown pour dire que l'adresse est inconnue

In [122]:
caract["adr"] = caract["adr"].fillna("Unknown")             # remplacement des cases vides
caract["adr"].isna().sum()                                  # Vérification du remplacement

np.int64(0)

Vérification des valeurs abérrantes

In [109]:
caract.describe(include= 'all')

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
count,5.440200e+04,54402.000000,54402.000000,54402.0,54402,54402.000000,54402,54402,54402.000000,54402.000000,54402.000000,54402.000000,54402,54402,54402
unique,NaN,NaN,NaN,NaN,1414,NaN,107,11285,NaN,NaN,NaN,NaN,28872,52471,52742
top,NaN,NaN,NaN,NaN,18:00,NaN,75,97302,NaN,NaN,NaN,NaN,Unknown,"48,91936344","5,40000000"
freq,NaN,NaN,NaN,NaN,677,NaN,4191,479,NaN,NaN,NaN,NaN,2310,8,9
mean,2.024000e+11,15.665490,6.615749,2024.0,NaN,1.949708,NaN,NaN,1.625161,2.108195,1.677493,4.018069,NaN,NaN,NaN
std,1.570465e+04,8.737761,3.361701,0.0,NaN,1.488462,NaN,NaN,0.484086,2.042602,1.736956,1.984560,NaN,NaN,NaN
min,2.024000e+11,1.000000,1.000000,2024.0,NaN,1.000000,NaN,NaN,1.000000,1.000000,1.000000,-1.000000,NaN,NaN,NaN
25%,2.024000e+11,8.000000,4.000000,2024.0,NaN,1.000000,NaN,NaN,1.000000,1.000000,1.000000,3.000000,NaN,NaN,NaN
50%,2.024000e+11,16.000000,7.000000,2024.0,NaN,1.000000,NaN,NaN,2.000000,1.000000,1.000000,3.000000,NaN,NaN,NaN
75%,2.024000e+11,23.000000,10.000000,2024.0,NaN,3.000000,NaN,NaN,2.000000,2.000000,1.000000,6.000000,NaN,NaN,NaN
max,2.024001e+11,31.000000,12.000000,2024.0,NaN,5.000000,NaN,NaN,2.000000,9.000000,9.000000,7.000000,NaN,NaN,NaN

Pas de valeur aberrante le min et le max de chaque attribut est respecté

In [123]:
caract["date"] = pd.to_datetime({
    "year": caract["an"],
    "month": caract["mois"],
    "day": caract["jour"],
})

caract.head()

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long,date
0,202400000001,25,3,2024,07:40,2,70,70285,1,1,5,1,D438,"47,56277000","6,75832000",2024-03-25
1,202400000002,20,3,2024,15:05,1,21,21054,2,3,7,6,HOTEL DIEU (RUE DE L'),"47,02109000","4,83755000",2024-03-20
2,202400000003,22,3,2024,19:30,2,15,15012,1,1,1,6,Allée des Tilleuls,"44,90238400","2,49641800",2024-03-22
3,202400000004,24,3,2024,17:50,1,14,14118,2,3,7,3,128 Rue d'Authie,"49,19166000","-0,39851000",2024-03-24
4,202400000005,25,3,2024,19:35,5,13,13106,1,3,2,5,BEDOULE (CHEMIN DE LA),"43,39000000","5,35000000",2024-03-25

On peut donc supprimer les attributs jour mois et an

In [131]:
caract.drop(["jour", "mois", "an"], axis=1, inplace=True)

In [132]:
caract.head()

,Num_Acc,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long,date
0,202400000001,07:40,2,70,70285,1,1,5,1,D438,"47,56277000","6,75832000",2024-03-25
1,202400000002,15:05,1,21,21054,2,3,7,6,HOTEL DIEU (RUE DE L'),"47,02109000","4,83755000",2024-03-20
2,202400000003,19:30,2,15,15012,1,1,1,6,Allée des Tilleuls,"44,90238400","2,49641800",2024-03-22
3,202400000004,17:50,1,14,14118,2,3,7,3,128 Rue d'Authie,"49,19166000","-0,39851000",2024-03-24
4,202400000005,19:35,5,13,13106,1,3,2,5,BEDOULE (CHEMIN DE LA),"43,39000000","5,35000000",2024-03-25